paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  js:
    path: _js
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  css:
    path: _css
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  products:
    path: _products
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  categories:
    - prime
    - odd
    - even
  sass:
    sass_dir: _scss
  pagination:
    enabled: true
    debug: false
    collection: posts
    per_page: 10
    permalink: /page/:num/
    title: ':title - page :num'
    limit: 0
    sort_field: date
    sort_reverse: true
    category: posts
    tag: ''
    locale: ''
    trail:
      before: 2
      after: 2
    extension: html
    indexpage: index
  autopages:
    enabled: true
    categories:
      layouts:
        - archive-auto.html
      title: Posts in category :cat
      permalink: /:cat
      silent: false
      slugify:
        mode: default
        case: false
    collections:
      layouts:
        - archive-auto.html
      title: Posts in collection :coll
      permalink: /collection/:coll
      silent: false
      slugify:
        mode: default
        case: false
    tags:
      layouts:
        - archive-auto.html
      title: Posts tagged with :tag
      permalink: /tag/:tag
      silent: false
      slugify:
        mode: default
        case: false
timezone: Etc/UTC
